services:
  asterisk:
    network_mode: "host"
    build: .
    container_name: asterisk
    volumes:
      - ./config:/etc/asterisk
      - ./etc/odbc.ini:/etc/odbc.ini
      - ./etc/odbcinst.ini:/etc/odbcinst.ini  
